Create script to output content models with validations
last-rev-llc/contentful-scripts pull request #26
Opened 2022-04-08 18:22 UTC by rochaeb

### Description
This script outputs a JSON file with information from all content models in a given Contentful environment. This adds on top of the script that produces a csv. It has some more information, like field validations and help text.

### Jira Ticket
[LRFA-335](https://lastrev.atlassian.net/browse/LRFA-335)

### How to test

### Preview URL
[Deploy Preview URL](https://example.com)

### Screenshots (if applicable)

### Changes include
- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] New Function
- [ ] New Route
- [ ] Documentation Update
- [ ] Other

2022-04-09 12:07 UTC, camiloriosf requested changes

2022-04-09 12:07 UTC, camiloriosf commented on jobs/exportContentModelSettingsJson.js
> +const JSON_FILE_PATH = '/home/rochaeb/Desktop/contentModels.json';
@rochaeb we should either put this in an env variable, pass it as an argument, store it in the same place the user runs the script, or add a comment so people know that they have to update this path.

2022-04-13 12:28 UTC, rochaeb commented on jobs/exportContentModelSettingsJson.js
> +const JSON_FILE_PATH = '/home/rochaeb/Desktop/contentModels.json';
Sure. I'll update it.

2022-04-13 13:09 UTC, camiloriosf approved these changes

2022-04-13 17:36 UTC, merged